### ISSUE TITLE
Circuit connections needed

### ISSUE THREAD

**Issue by h20180180** [leoll2/SpeedoMeter#1]
Can you provide the circuit diagram with all the connections of transistors, leds , pir sensors and gpio pins of the raspberry pi ?

**Comment by leoll2** [comment]
I'm afraid I didn't make any scheme for that project, and I disassembled the circuit time ago. Anyway, it shouldn't be too complicated to retrieve a working configuration given the available pictures and the source code. Some information about pin-mapping is also present in the code files.
Regarding the 4-digit display, the position of the pins may vary from model to model, hence I recommend you to read the datasheet of your component. Nevertheless, the meaning of segment {A...G} is universal for all 7-segments displays, you can easily find it online.
 LEDs were hard-wired to the PIR sensor, to immediately trigger when something moves; in other words, the LEDs are not directly driven by the raspberry.
The position and size of resistors can be obtained with simple electronic considerations, based on the operating voltages and currents of RPi and components (follow the datasheets). Transistors are generally arranged to act as switches, with the GPIO pins (I mean the digital output ones) driving their bases; the other two terminals are either connected to the component or 5V/gnd. I don't remember if I adopted a common emitter or collector configuration, both should viable though.
My bad for forgetting to draw the diagram, lesson learned!
